<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="icon" href="<?= $this->basePath() ?>/public/img/favicon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="<?= $this->basePath() ?>/public/img/favicon.png" />

    <!-- responsive metatag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <?php $this->setTitle('My App'); $_title = $this->getTitle(); ?>

    <title><?= $this->getTitle() ?></title>

    <link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/bootstrap.min.css" />

    <script src="<?= $this->basePath(); ?>/public/js/jquery-3.3.1.min.js"></script>
    <script src="<?= $this->basePath(); ?>/public/js/popper-1.12.9.min.js"></script>
    <script src="<?= $this->basePath(); ?>/public/js/bootstrap.min.js"></script>

    <script src="<?= $this->basePath(); ?>/public/js/easyajax.js"></script>

    <style>
        /*
         * For more straightforward sizing in CSS, we switch the global box-sizing value from content-box to border-box.
         * This ensures padding does not affect the final computed width of an element, but it can cause problems with
         * some third party software like Google Maps and Google Custom Search Engine.
         *
         * On the rare occasion you need to override it, use the following class
         */

        .content-box-widget {
             box-sizing: content-box;
        }

        /* Extra small devices (portrait phones, less than 576px)
          No media query since this is the default in Bootstrap */

        /* Small devices (landscape phones, 576px and up) */
        @media (min-width: 576px) { ... }

        /* Medium devices (tablets, 768px and up) */
        @media (min-width: 768px) { ... }

        /* Large devices (desktops, 992px and up) */
        @media (min-width: 992px) { ... }

        /* Extra large devices (large desktops, 1200px and up) */
        @media (min-width: 1200px) { ... }

        /* Exclusive media queries following */

        /* Extra small devices (portrait phones, less than 576px) */
        @media (max-width: 575.98px) { ... }

        /* Small devices (landscape phones, 576px and up) */
        @media (min-width: 576px) and (max-width: 767.98px) { ... }

        /* Medium devices (tablets, 768px and up) */
        @media (min-width: 768px) and (max-width: 991.98px) { ... }

        /* Large devices (desktops, 992px and up) */
        @media (min-width: 992px) and (max-width: 1199.98px) { ... }

        /* Extra large devices (large desktops, 1200px and up) */
        @media (min-width: 1200px) { ... }

    </style>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<?= $this->basePath() ?>">
          <img src="<?= $this->basePath() ?>/public/img/bootstrap-solid.svg" height="30" width="30" class="d-inline-block align-top" alt="">
          PlacetoPay
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<?= $this->basePath() ?>/App/Pagos/index">Pago PSE <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav><br />

    <div class="container">
        <?= $this->content() ?>
    </div>

    <!-- update page title -->
    <?php if ($this->getTitle() !== $_title): ?>
        <script type="text/javascript">
            $("head title").text($("head title").text() + ' - <?= $this->getTitle() ?>');
        </script>
    <?php endif; ?>

</body>

</html>